"""PATH-based shim binaries for transparent output compression.

Creates lightweight bash scripts in ~/.local/share/mto/shims/ that intercept
common dev commands and pipe their output through `mto proxy`.

IMPORTANT: Shims are NEVER added to the user's shell rc files.
They only activate when:
  1. An agent launches with PATH explicitly set (e.g. via agent wrapper script)
  2. The user explicitly runs `eval "$(mto shims-env)"` in a session
  3. A tool spawns subprocesses with the shim PATH inherited

This ensures the user's normal interactive shell is never affected.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

SHIM_DIR = Path.home() / ".local" / "share" / "mto" / "shims"

DEFAULT_COMMANDS = [
    "git", "docker", "kubectl", "cargo", "npm", "pnpm", "yarn",
    "pytest", "go", "ruff", "eslint", "grep", "find", "ls", "cat",
    "ps", "df", "du",
]

# Only activate when MTO_SHIMS_ACTIVE=1 is set in the environment.
# This prevents accidental activation if the shim dir somehow ends up on PATH.
_SHIM_TEMPLATE = r'''#!/usr/bin/env bash
# mto shim: transparent output compression for {cmd}
# Auto-generated by `mto install-shims`. Do not edit.
# Only active when MTO_SHIMS_ACTIVE=1 (set by `mto shims-env` or agent wrappers).

_mto_find_real() {{
  local shim_dir
  shim_dir="$(cd "$(dirname "$0")" && pwd)"
  local IFS=':'
  for dir in $PATH; do
    [[ "$dir" == "$shim_dir" ]] && continue
    [[ -x "$dir/{cmd}" ]] && echo "$dir/{cmd}" && return
  done
  echo "{cmd}"
}}

_mto_real="$(_mto_find_real)"

# Only compress when explicitly activated for agent sessions
if [[ "${{MTO_SHIMS_ACTIVE:-0}}" != "1" ]] || [[ "${{MTO_DISABLED:-0}}" == "1" ]]; then
  exec "$_mto_real" "$@"
fi

# If mto binary is not available, fall back to real command
if ! command -v mto >/dev/null 2>&1; then
  exec "$_mto_real" "$@"
fi

# Write-modifying commands: pass through without compression
case "{cmd}" in
  git)
    case "${{1:-}}" in
      push|pull|fetch|merge|rebase|reset|checkout|switch|commit|stash|cherry-pick|am|mv|rm|clean|clone|init|tag)
        exec "$_mto_real" "$@" ;;
    esac ;;
  docker)
    case "${{1:-}}" in
      run|exec|start|stop|rm|rmi|build|push|pull|kill|pause|unpause|create|cp)
        exec "$_mto_real" "$@" ;;
    esac ;;
  kubectl)
    case "${{1:-}}" in
      apply|delete|create|patch|replace|scale|rollout|edit|exec|cp)
        exec "$_mto_real" "$@" ;;
    esac ;;
  npm|pnpm|yarn)
    case "${{1:-}}" in
      install|uninstall|add|remove|publish|init|create|link|pack)
        exec "$_mto_real" "$@" ;;
    esac ;;
  cargo)
    case "${{1:-}}" in
      publish|install|uninstall|init|new|add|remove|fix)
        exec "$_mto_real" "$@" ;;
    esac ;;
  go)
    case "${{1:-}}" in
      install|get|mod|generate|clean|fix)
        exec "$_mto_real" "$@" ;;
    esac ;;
esac

exec mto proxy -- "$_mto_real" "$@"
'''


def install_shims(
    commands: list[str] | None = None,
    shim_dir: Path | None = None,
) -> list[Path]:
    """Create shim scripts for specified commands. Returns list of created paths."""
    commands = commands or DEFAULT_COMMANDS
    target = shim_dir or SHIM_DIR
    target.mkdir(parents=True, exist_ok=True)
    created = []
    for cmd in commands:
        path = target / cmd
        path.write_text(_SHIM_TEMPLATE.format(cmd=cmd), encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        created.append(path)
    return created


def uninstall_shims(shim_dir: Path | None = None) -> list[Path]:
    """Remove all shim scripts. Returns list of removed paths."""
    target = shim_dir or SHIM_DIR
    removed = []
    if not target.exists():
        return removed
    for path in target.iterdir():
        if path.is_file():
            path.unlink()
            removed.append(path)
    try:
        target.rmdir()
    except OSError:
        pass
    return removed


def get_shims_env(shim_dir: Path | None = None) -> str:
    """Return shell snippet that activates shims for the current session only."""
    target = shim_dir or SHIM_DIR
    return f'export PATH="{target}:$PATH"\nexport MTO_SHIMS_ACTIVE=1'
